
name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      CSC_LINK: ${{ secrets.CSC_LINK }}          # optional: code signing cert (PFX) as secure file or base64 uri
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # auto provided; or create PAT with repo scope
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build Windows (publish to GitHub Releases)
        run: npx electron-builder -w --publish always
