
name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write   # needed to create/update releases
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        # provided automatically
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}  # optional
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # Decode base64 PFX only if the secret is defined
      - name: Prepare code-signing cert (optional)
        shell: pwsh
        env:
          CSC_LINK_B64: ${{ secrets.CSC_LINK_B64 }}
        run: |
          if ($env:CSC_LINK_B64) {
            Write-Host "Code signing: decoding PFX from CSC_LINK_B64"
            $bytes = [Convert]::FromBase64String($env:CSC_LINK_B64)
            $pfxPath = "$env:RUNNER_TEMP\codesign.pfx"
            [IO.File]::WriteAllBytes($pfxPath, $bytes)
            # Expose CSC_LINK for electron-builder
            "CSC_LINK=file:///$pfxPath" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          } else {
            Write-Host "No CSC_LINK_B64 provided; building unsigned artifacts."
          }

      - name: Build Windows and publish to GitHub Releases
        run: npx electron-builder -w --publish always

      - name: Compute SHA256 checksums of built EXEs
        shell: pwsh
        run: |
          $dist = Resolve-Path dist
          $files = Get-ChildItem $dist -Filter *.exe -File
          if ($files.Count -eq 0) {
            Write-Error "No .exe files found in dist/"
          }
          $out = ""
          foreach ($f in $files) {
            $hash = (Get-FileHash $f.FullName -Algorithm SHA256).Hash
            $out += "$($f.Name)  $hash`n"
          }
          $out | Out-File -FilePath "$dist\checksums.txt" -Encoding utf8
          Get-Content "$dist\checksums.txt"

      - name: Fill release notes from template with checksums
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const core = require('@actions/core');
            const version = require(path.join(process.env.GITHUB_WORKSPACE, 'package.json')).version;
            const tag = process.env.GITHUB_REF_NAME; // e.g., v1.5.0
            const templatePath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'release_template.md');
            let body = fs.readFileSync(templatePath, 'utf8');

            // Replace $VERSION placeholder
            body = body.replace(/\$VERSION/g, version);

            // Read checksums (if present)
            const sumsPath = path.join(process.env.GITHUB_WORKSPACE, 'dist', 'checksums.txt');
            let sums = '(checksums unavailable)';
            try {
              sums = fs.readFileSync(sumsPath, 'utf8').trim();
            } catch (e) {}

            // Put checksums where template says (paste checksum here)
            body = body.replace('(paste checksum here)', sums);

            // Update the release body for this tag
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: body
            });
